image: node:15

# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

test_async:
  script:
    - npm install
    - node ./node_modules/.bin/eslint src/ tests/ example/
    - node ./node_modules/.bin/jest
    - node ./node_modules/.bin/webpack

